
namespace eCONSTRUCTION
{
    partial class FormAddSite
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FormAddSite));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties29 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties30 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties31 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties32 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuImageButton1 = new Bunifu.UI.WinForms.BunifuImageButton();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.bunifuElipse1 = new Bunifu.Framework.UI.BunifuElipse(this.components);
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.textboxCountry = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel5 = new Bunifu.UI.WinForms.BunifuLabel();
            this.textboxCity = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel6 = new Bunifu.UI.WinForms.BunifuLabel();
            this.textboxStreet = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel7 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel8 = new Bunifu.UI.WinForms.BunifuLabel();
            this.textboxLongitude = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel9 = new Bunifu.UI.WinForms.BunifuLabel();
            this.textboxLatitude = new Bunifu.UI.WinForms.BunifuTextBox();
            this.buttonAdd = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.textboxArea = new Bunifu.UI.WinForms.BunifuTextBox();
            this.textboxPricePerMeter = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.textboxSiteName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.panel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.panel1.Controls.Add(this.bunifuImageButton1);
            this.panel1.Controls.Add(this.bunifuLabel1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Name = "panel1";
            this.panel1.Size = new System.Drawing.Size(687, 34);
            this.panel1.TabIndex = 19;
            // 
            // bunifuImageButton1
            // 
            this.bunifuImageButton1.ActiveImage = null;
            this.bunifuImageButton1.AllowAnimations = true;
            this.bunifuImageButton1.AllowBuffering = false;
            this.bunifuImageButton1.AllowToggling = false;
            this.bunifuImageButton1.AllowZooming = true;
            this.bunifuImageButton1.AllowZoomingOnFocus = false;
            this.bunifuImageButton1.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right)));
            this.bunifuImageButton1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuImageButton1.Cursor = System.Windows.Forms.Cursors.Hand;
            this.bunifuImageButton1.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuImageButton1.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.ErrorImage")));
            this.bunifuImageButton1.FadeWhenInactive = false;
            this.bunifuImageButton1.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bunifuImageButton1.Image = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.Image")));
            this.bunifuImageButton1.ImageActive = null;
            this.bunifuImageButton1.ImageLocation = null;
            this.bunifuImageButton1.ImageMargin = 0;
            this.bunifuImageButton1.ImageSize = new System.Drawing.Size(19, 19);
            this.bunifuImageButton1.ImageZoomSize = new System.Drawing.Size(20, 20);
            this.bunifuImageButton1.InitialImage = ((System.Drawing.Image)(resources.GetObject("bunifuImageButton1.InitialImage")));
            this.bunifuImageButton1.Location = new System.Drawing.Point(655, 7);
            this.bunifuImageButton1.Name = "bunifuImageButton1";
            this.bunifuImageButton1.Rotation = 0;
            this.bunifuImageButton1.ShowActiveImage = true;
            this.bunifuImageButton1.ShowCursorChanges = true;
            this.bunifuImageButton1.ShowImageBorders = false;
            this.bunifuImageButton1.ShowSizeMarkers = false;
            this.bunifuImageButton1.Size = new System.Drawing.Size(20, 20);
            this.bunifuImageButton1.TabIndex = 2;
            this.bunifuImageButton1.ToolTipText = "";
            this.bunifuImageButton1.WaitOnLoad = false;
            this.bunifuImageButton1.Zoom = 0;
            this.bunifuImageButton1.ZoomSpeed = 10;
            this.bunifuImageButton1.Click += new System.EventHandler(this.bunifuImageButton1_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.CursorType = null;
            this.bunifuLabel1.Font = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(48)))), ((int)(((byte)(48)))), ((int)(((byte)(58)))));
            this.bunifuLabel1.Location = new System.Drawing.Point(12, 7);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(63, 18);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "ADD SITE";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopCenter;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = false;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = false;
            this.bunifuFormDock1.ShowDockingIndicators = false;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // bunifuElipse1
            // 
            this.bunifuElipse1.ElipseRadius = 20;
            this.bunifuElipse1.TargetControl = this;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.CursorType = null;
            this.bunifuLabel3.Font = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel3.Location = new System.Drawing.Point(372, 233);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(110, 18);
            this.bunifuLabel3.TabIndex = 23;
            this.bunifuLabel3.Text = "Site Area in m²:";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.CursorType = null;
            this.bunifuLabel4.Font = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel4.Location = new System.Drawing.Point(13, 141);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(62, 18);
            this.bunifuLabel4.TabIndex = 25;
            this.bunifuLabel4.Text = "Country:";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // textboxCountry
            // 
            this.textboxCountry.AcceptsReturn = false;
            this.textboxCountry.AcceptsTab = false;
            this.textboxCountry.AnimationSpeed = 200;
            this.textboxCountry.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textboxCountry.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textboxCountry.BackColor = System.Drawing.Color.Transparent;
            this.textboxCountry.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textboxCountry.BackgroundImage")));
            this.textboxCountry.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxCountry.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textboxCountry.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxCountry.BorderColorIdle = System.Drawing.Color.Transparent;
            this.textboxCountry.BorderRadius = 13;
            this.textboxCountry.BorderThickness = 1;
            this.textboxCountry.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textboxCountry.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxCountry.DefaultFont = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textboxCountry.DefaultText = "";
            this.textboxCountry.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            this.textboxCountry.ForeColor = System.Drawing.Color.White;
            this.textboxCountry.HideSelection = true;
            this.textboxCountry.IconLeft = null;
            this.textboxCountry.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxCountry.IconPadding = 10;
            this.textboxCountry.IconRight = null;
            this.textboxCountry.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxCountry.Lines = new string[0];
            this.textboxCountry.Location = new System.Drawing.Point(13, 165);
            this.textboxCountry.MaxLength = 32767;
            this.textboxCountry.MinimumSize = new System.Drawing.Size(1, 1);
            this.textboxCountry.Modified = false;
            this.textboxCountry.Multiline = false;
            this.textboxCountry.Name = "textboxCountry";
            stateProperties29.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties29.FillColor = System.Drawing.Color.Empty;
            stateProperties29.ForeColor = System.Drawing.Color.Empty;
            stateProperties29.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxCountry.OnActiveState = stateProperties29;
            stateProperties30.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties30.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties30.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties30.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textboxCountry.OnDisabledState = stateProperties30;
            stateProperties31.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties31.FillColor = System.Drawing.Color.Empty;
            stateProperties31.ForeColor = System.Drawing.Color.Empty;
            stateProperties31.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxCountry.OnHoverState = stateProperties31;
            stateProperties32.BorderColor = System.Drawing.Color.Transparent;
            stateProperties32.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            stateProperties32.ForeColor = System.Drawing.Color.White;
            stateProperties32.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxCountry.OnIdleState = stateProperties32;
            this.textboxCountry.Padding = new System.Windows.Forms.Padding(3);
            this.textboxCountry.PasswordChar = '\0';
            this.textboxCountry.PlaceholderForeColor = System.Drawing.Color.White;
            this.textboxCountry.PlaceholderText = "Enter text";
            this.textboxCountry.ReadOnly = false;
            this.textboxCountry.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textboxCountry.SelectedText = "";
            this.textboxCountry.SelectionLength = 0;
            this.textboxCountry.SelectionStart = 0;
            this.textboxCountry.ShortcutsEnabled = true;
            this.textboxCountry.Size = new System.Drawing.Size(297, 39);
            this.textboxCountry.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textboxCountry.TabIndex = 24;
            this.textboxCountry.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textboxCountry.TextMarginBottom = 0;
            this.textboxCountry.TextMarginLeft = 3;
            this.textboxCountry.TextMarginTop = 0;
            this.textboxCountry.TextPlaceholder = "Enter text";
            this.textboxCountry.UseSystemPasswordChar = false;
            this.textboxCountry.WordWrap = true;
            // 
            // bunifuLabel5
            // 
            this.bunifuLabel5.AllowParentOverrides = false;
            this.bunifuLabel5.AutoEllipsis = false;
            this.bunifuLabel5.CursorType = null;
            this.bunifuLabel5.Font = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel5.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel5.Location = new System.Drawing.Point(13, 233);
            this.bunifuLabel5.Name = "bunifuLabel5";
            this.bunifuLabel5.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel5.Size = new System.Drawing.Size(33, 18);
            this.bunifuLabel5.TabIndex = 27;
            this.bunifuLabel5.Text = "City:";
            this.bunifuLabel5.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel5.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // textboxCity
            // 
            this.textboxCity.AcceptsReturn = false;
            this.textboxCity.AcceptsTab = false;
            this.textboxCity.AnimationSpeed = 200;
            this.textboxCity.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textboxCity.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textboxCity.BackColor = System.Drawing.Color.Transparent;
            this.textboxCity.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textboxCity.BackgroundImage")));
            this.textboxCity.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxCity.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textboxCity.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxCity.BorderColorIdle = System.Drawing.Color.Transparent;
            this.textboxCity.BorderRadius = 13;
            this.textboxCity.BorderThickness = 1;
            this.textboxCity.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textboxCity.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxCity.DefaultFont = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textboxCity.DefaultText = "";
            this.textboxCity.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            this.textboxCity.ForeColor = System.Drawing.Color.White;
            this.textboxCity.HideSelection = true;
            this.textboxCity.IconLeft = null;
            this.textboxCity.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxCity.IconPadding = 10;
            this.textboxCity.IconRight = null;
            this.textboxCity.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxCity.Lines = new string[0];
            this.textboxCity.Location = new System.Drawing.Point(13, 257);
            this.textboxCity.MaxLength = 32767;
            this.textboxCity.MinimumSize = new System.Drawing.Size(1, 1);
            this.textboxCity.Modified = false;
            this.textboxCity.Multiline = false;
            this.textboxCity.Name = "textboxCity";
            stateProperties25.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxCity.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textboxCity.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxCity.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Transparent;
            stateProperties28.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            stateProperties28.ForeColor = System.Drawing.Color.White;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxCity.OnIdleState = stateProperties28;
            this.textboxCity.Padding = new System.Windows.Forms.Padding(3);
            this.textboxCity.PasswordChar = '\0';
            this.textboxCity.PlaceholderForeColor = System.Drawing.Color.White;
            this.textboxCity.PlaceholderText = "Enter text";
            this.textboxCity.ReadOnly = false;
            this.textboxCity.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textboxCity.SelectedText = "";
            this.textboxCity.SelectionLength = 0;
            this.textboxCity.SelectionStart = 0;
            this.textboxCity.ShortcutsEnabled = true;
            this.textboxCity.Size = new System.Drawing.Size(297, 39);
            this.textboxCity.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textboxCity.TabIndex = 26;
            this.textboxCity.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textboxCity.TextMarginBottom = 0;
            this.textboxCity.TextMarginLeft = 3;
            this.textboxCity.TextMarginTop = 0;
            this.textboxCity.TextPlaceholder = "Enter text";
            this.textboxCity.UseSystemPasswordChar = false;
            this.textboxCity.WordWrap = true;
            // 
            // bunifuLabel6
            // 
            this.bunifuLabel6.AllowParentOverrides = false;
            this.bunifuLabel6.AutoEllipsis = false;
            this.bunifuLabel6.CursorType = null;
            this.bunifuLabel6.Font = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel6.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel6.Location = new System.Drawing.Point(13, 324);
            this.bunifuLabel6.Name = "bunifuLabel6";
            this.bunifuLabel6.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel6.Size = new System.Drawing.Size(45, 18);
            this.bunifuLabel6.TabIndex = 29;
            this.bunifuLabel6.Text = "Street:";
            this.bunifuLabel6.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel6.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // textboxStreet
            // 
            this.textboxStreet.AcceptsReturn = false;
            this.textboxStreet.AcceptsTab = false;
            this.textboxStreet.AnimationSpeed = 200;
            this.textboxStreet.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textboxStreet.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textboxStreet.BackColor = System.Drawing.Color.Transparent;
            this.textboxStreet.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textboxStreet.BackgroundImage")));
            this.textboxStreet.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxStreet.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textboxStreet.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxStreet.BorderColorIdle = System.Drawing.Color.Transparent;
            this.textboxStreet.BorderRadius = 13;
            this.textboxStreet.BorderThickness = 1;
            this.textboxStreet.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textboxStreet.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxStreet.DefaultFont = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textboxStreet.DefaultText = "";
            this.textboxStreet.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            this.textboxStreet.ForeColor = System.Drawing.Color.White;
            this.textboxStreet.HideSelection = true;
            this.textboxStreet.IconLeft = null;
            this.textboxStreet.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxStreet.IconPadding = 10;
            this.textboxStreet.IconRight = null;
            this.textboxStreet.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxStreet.Lines = new string[0];
            this.textboxStreet.Location = new System.Drawing.Point(13, 348);
            this.textboxStreet.MaxLength = 32767;
            this.textboxStreet.MinimumSize = new System.Drawing.Size(1, 1);
            this.textboxStreet.Modified = false;
            this.textboxStreet.Multiline = false;
            this.textboxStreet.Name = "textboxStreet";
            stateProperties21.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxStreet.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textboxStreet.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxStreet.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Transparent;
            stateProperties24.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            stateProperties24.ForeColor = System.Drawing.Color.White;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxStreet.OnIdleState = stateProperties24;
            this.textboxStreet.Padding = new System.Windows.Forms.Padding(3);
            this.textboxStreet.PasswordChar = '\0';
            this.textboxStreet.PlaceholderForeColor = System.Drawing.Color.White;
            this.textboxStreet.PlaceholderText = "Enter text";
            this.textboxStreet.ReadOnly = false;
            this.textboxStreet.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textboxStreet.SelectedText = "";
            this.textboxStreet.SelectionLength = 0;
            this.textboxStreet.SelectionStart = 0;
            this.textboxStreet.ShortcutsEnabled = true;
            this.textboxStreet.Size = new System.Drawing.Size(297, 39);
            this.textboxStreet.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textboxStreet.TabIndex = 28;
            this.textboxStreet.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textboxStreet.TextMarginBottom = 0;
            this.textboxStreet.TextMarginLeft = 3;
            this.textboxStreet.TextMarginTop = 0;
            this.textboxStreet.TextPlaceholder = "Enter text";
            this.textboxStreet.UseSystemPasswordChar = false;
            this.textboxStreet.WordWrap = true;
            // 
            // bunifuLabel7
            // 
            this.bunifuLabel7.AllowParentOverrides = false;
            this.bunifuLabel7.AutoEllipsis = false;
            this.bunifuLabel7.CursorType = null;
            this.bunifuLabel7.Font = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel7.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel7.Location = new System.Drawing.Point(547, 233);
            this.bunifuLabel7.Name = "bunifuLabel7";
            this.bunifuLabel7.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel7.Size = new System.Drawing.Size(122, 18);
            this.bunifuLabel7.TabIndex = 31;
            this.bunifuLabel7.Text = "Price per m² in $:";
            this.bunifuLabel7.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel7.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuLabel8
            // 
            this.bunifuLabel8.AllowParentOverrides = false;
            this.bunifuLabel8.AutoEllipsis = false;
            this.bunifuLabel8.CursorType = null;
            this.bunifuLabel8.Font = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel8.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel8.Location = new System.Drawing.Point(372, 58);
            this.bunifuLabel8.Name = "bunifuLabel8";
            this.bunifuLabel8.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel8.Size = new System.Drawing.Size(77, 18);
            this.bunifuLabel8.TabIndex = 34;
            this.bunifuLabel8.Text = "Longitude:";
            this.bunifuLabel8.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel8.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // textboxLongitude
            // 
            this.textboxLongitude.AcceptsReturn = false;
            this.textboxLongitude.AcceptsTab = false;
            this.textboxLongitude.AnimationSpeed = 200;
            this.textboxLongitude.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textboxLongitude.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textboxLongitude.BackColor = System.Drawing.Color.Transparent;
            this.textboxLongitude.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textboxLongitude.BackgroundImage")));
            this.textboxLongitude.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxLongitude.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textboxLongitude.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxLongitude.BorderColorIdle = System.Drawing.Color.Transparent;
            this.textboxLongitude.BorderRadius = 13;
            this.textboxLongitude.BorderThickness = 1;
            this.textboxLongitude.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textboxLongitude.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxLongitude.DefaultFont = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textboxLongitude.DefaultText = "";
            this.textboxLongitude.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            this.textboxLongitude.ForeColor = System.Drawing.Color.White;
            this.textboxLongitude.HideSelection = true;
            this.textboxLongitude.IconLeft = null;
            this.textboxLongitude.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxLongitude.IconPadding = 10;
            this.textboxLongitude.IconRight = null;
            this.textboxLongitude.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxLongitude.Lines = new string[0];
            this.textboxLongitude.Location = new System.Drawing.Point(372, 82);
            this.textboxLongitude.MaxLength = 32767;
            this.textboxLongitude.MinimumSize = new System.Drawing.Size(1, 1);
            this.textboxLongitude.Modified = false;
            this.textboxLongitude.Multiline = false;
            this.textboxLongitude.Name = "textboxLongitude";
            stateProperties17.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxLongitude.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textboxLongitude.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxLongitude.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Transparent;
            stateProperties20.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            stateProperties20.ForeColor = System.Drawing.Color.White;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxLongitude.OnIdleState = stateProperties20;
            this.textboxLongitude.Padding = new System.Windows.Forms.Padding(3);
            this.textboxLongitude.PasswordChar = '\0';
            this.textboxLongitude.PlaceholderForeColor = System.Drawing.Color.White;
            this.textboxLongitude.PlaceholderText = "Enter text";
            this.textboxLongitude.ReadOnly = false;
            this.textboxLongitude.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textboxLongitude.SelectedText = "";
            this.textboxLongitude.SelectionLength = 0;
            this.textboxLongitude.SelectionStart = 0;
            this.textboxLongitude.ShortcutsEnabled = true;
            this.textboxLongitude.Size = new System.Drawing.Size(297, 39);
            this.textboxLongitude.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textboxLongitude.TabIndex = 33;
            this.textboxLongitude.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textboxLongitude.TextMarginBottom = 0;
            this.textboxLongitude.TextMarginLeft = 3;
            this.textboxLongitude.TextMarginTop = 0;
            this.textboxLongitude.TextPlaceholder = "Enter text";
            this.textboxLongitude.UseSystemPasswordChar = false;
            this.textboxLongitude.WordWrap = true;
            // 
            // bunifuLabel9
            // 
            this.bunifuLabel9.AllowParentOverrides = false;
            this.bunifuLabel9.AutoEllipsis = false;
            this.bunifuLabel9.CursorType = null;
            this.bunifuLabel9.Font = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel9.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel9.Location = new System.Drawing.Point(372, 141);
            this.bunifuLabel9.Name = "bunifuLabel9";
            this.bunifuLabel9.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel9.Size = new System.Drawing.Size(62, 18);
            this.bunifuLabel9.TabIndex = 36;
            this.bunifuLabel9.Text = "Latitude:";
            this.bunifuLabel9.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel9.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // textboxLatitude
            // 
            this.textboxLatitude.AcceptsReturn = false;
            this.textboxLatitude.AcceptsTab = false;
            this.textboxLatitude.AnimationSpeed = 200;
            this.textboxLatitude.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textboxLatitude.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textboxLatitude.BackColor = System.Drawing.Color.Transparent;
            this.textboxLatitude.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textboxLatitude.BackgroundImage")));
            this.textboxLatitude.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxLatitude.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textboxLatitude.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxLatitude.BorderColorIdle = System.Drawing.Color.Transparent;
            this.textboxLatitude.BorderRadius = 13;
            this.textboxLatitude.BorderThickness = 1;
            this.textboxLatitude.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textboxLatitude.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxLatitude.DefaultFont = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textboxLatitude.DefaultText = "";
            this.textboxLatitude.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            this.textboxLatitude.ForeColor = System.Drawing.Color.White;
            this.textboxLatitude.HideSelection = true;
            this.textboxLatitude.IconLeft = null;
            this.textboxLatitude.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxLatitude.IconPadding = 10;
            this.textboxLatitude.IconRight = null;
            this.textboxLatitude.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxLatitude.Lines = new string[0];
            this.textboxLatitude.Location = new System.Drawing.Point(371, 165);
            this.textboxLatitude.MaxLength = 32767;
            this.textboxLatitude.MinimumSize = new System.Drawing.Size(1, 1);
            this.textboxLatitude.Modified = false;
            this.textboxLatitude.Multiline = false;
            this.textboxLatitude.Name = "textboxLatitude";
            stateProperties13.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxLatitude.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textboxLatitude.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxLatitude.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Transparent;
            stateProperties16.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            stateProperties16.ForeColor = System.Drawing.Color.White;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxLatitude.OnIdleState = stateProperties16;
            this.textboxLatitude.Padding = new System.Windows.Forms.Padding(3);
            this.textboxLatitude.PasswordChar = '\0';
            this.textboxLatitude.PlaceholderForeColor = System.Drawing.Color.White;
            this.textboxLatitude.PlaceholderText = "Enter text";
            this.textboxLatitude.ReadOnly = false;
            this.textboxLatitude.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textboxLatitude.SelectedText = "";
            this.textboxLatitude.SelectionLength = 0;
            this.textboxLatitude.SelectionStart = 0;
            this.textboxLatitude.ShortcutsEnabled = true;
            this.textboxLatitude.Size = new System.Drawing.Size(297, 39);
            this.textboxLatitude.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textboxLatitude.TabIndex = 35;
            this.textboxLatitude.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textboxLatitude.TextMarginBottom = 0;
            this.textboxLatitude.TextMarginLeft = 3;
            this.textboxLatitude.TextMarginTop = 0;
            this.textboxLatitude.TextPlaceholder = "Enter text";
            this.textboxLatitude.UseSystemPasswordChar = false;
            this.textboxLatitude.WordWrap = true;
            // 
            // buttonAdd
            // 
            this.buttonAdd.AllowAnimations = true;
            this.buttonAdd.AllowMouseEffects = true;
            this.buttonAdd.AllowToggling = false;
            this.buttonAdd.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.buttonAdd.AnimationSpeed = 200;
            this.buttonAdd.AutoGenerateColors = false;
            this.buttonAdd.AutoRoundBorders = false;
            this.buttonAdd.AutoSizeLeftIcon = true;
            this.buttonAdd.AutoSizeRightIcon = true;
            this.buttonAdd.BackColor = System.Drawing.Color.Transparent;
            this.buttonAdd.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(166)))), ((int)(((byte)(10)))));
            this.buttonAdd.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("buttonAdd.BackgroundImage")));
            this.buttonAdd.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonAdd.ButtonText = "Add Site";
            this.buttonAdd.ButtonTextMarginLeft = 0;
            this.buttonAdd.ColorContrastOnClick = 45;
            this.buttonAdd.ColorContrastOnHover = 45;
            this.buttonAdd.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.buttonAdd.CustomizableEdges = borderEdges1;
            this.buttonAdd.DialogResult = System.Windows.Forms.DialogResult.None;
            this.buttonAdd.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonAdd.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonAdd.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonAdd.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.buttonAdd.Font = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.buttonAdd.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(48)))), ((int)(((byte)(48)))), ((int)(((byte)(58)))));
            this.buttonAdd.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.buttonAdd.IconLeftCursor = System.Windows.Forms.Cursors.Hand;
            this.buttonAdd.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.buttonAdd.IconMarginLeft = 11;
            this.buttonAdd.IconPadding = 10;
            this.buttonAdd.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.buttonAdd.IconRightCursor = System.Windows.Forms.Cursors.Hand;
            this.buttonAdd.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.buttonAdd.IconSize = 25;
            this.buttonAdd.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(166)))), ((int)(((byte)(10)))));
            this.buttonAdd.IdleBorderRadius = 13;
            this.buttonAdd.IdleBorderThickness = 3;
            this.buttonAdd.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(166)))), ((int)(((byte)(10)))));
            this.buttonAdd.IdleIconLeftImage = null;
            this.buttonAdd.IdleIconRightImage = null;
            this.buttonAdd.IndicateFocus = false;
            this.buttonAdd.Location = new System.Drawing.Point(546, 336);
            this.buttonAdd.Name = "buttonAdd";
            this.buttonAdd.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.buttonAdd.OnDisabledState.BorderRadius = 13;
            this.buttonAdd.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonAdd.OnDisabledState.BorderThickness = 3;
            this.buttonAdd.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.buttonAdd.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.buttonAdd.OnDisabledState.IconLeftImage = null;
            this.buttonAdd.OnDisabledState.IconRightImage = null;
            this.buttonAdd.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(177)))), ((int)(((byte)(51)))));
            this.buttonAdd.onHoverState.BorderRadius = 13;
            this.buttonAdd.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonAdd.onHoverState.BorderThickness = 3;
            this.buttonAdd.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(177)))), ((int)(((byte)(51)))));
            this.buttonAdd.onHoverState.ForeColor = System.Drawing.Color.Black;
            this.buttonAdd.onHoverState.IconLeftImage = null;
            this.buttonAdd.onHoverState.IconRightImage = null;
            this.buttonAdd.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(166)))), ((int)(((byte)(10)))));
            this.buttonAdd.OnIdleState.BorderRadius = 13;
            this.buttonAdd.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonAdd.OnIdleState.BorderThickness = 3;
            this.buttonAdd.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(166)))), ((int)(((byte)(10)))));
            this.buttonAdd.OnIdleState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(48)))), ((int)(((byte)(48)))), ((int)(((byte)(58)))));
            this.buttonAdd.OnIdleState.IconLeftImage = null;
            this.buttonAdd.OnIdleState.IconRightImage = null;
            this.buttonAdd.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(177)))), ((int)(((byte)(51)))));
            this.buttonAdd.OnPressedState.BorderRadius = 13;
            this.buttonAdd.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.buttonAdd.OnPressedState.BorderThickness = 3;
            this.buttonAdd.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(177)))), ((int)(((byte)(51)))));
            this.buttonAdd.OnPressedState.ForeColor = System.Drawing.Color.Black;
            this.buttonAdd.OnPressedState.IconLeftImage = null;
            this.buttonAdd.OnPressedState.IconRightImage = null;
            this.buttonAdd.Size = new System.Drawing.Size(123, 63);
            this.buttonAdd.TabIndex = 37;
            this.buttonAdd.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.buttonAdd.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.buttonAdd.TextMarginLeft = 0;
            this.buttonAdd.TextPadding = new System.Windows.Forms.Padding(0);
            this.buttonAdd.UseDefaultRadiusAndThickness = true;
            this.buttonAdd.Click += new System.EventHandler(this.buttonAdd_Click);
            // 
            // textboxArea
            // 
            this.textboxArea.AcceptsReturn = false;
            this.textboxArea.AcceptsTab = false;
            this.textboxArea.AnimationSpeed = 200;
            this.textboxArea.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textboxArea.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textboxArea.BackColor = System.Drawing.Color.Transparent;
            this.textboxArea.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textboxArea.BackgroundImage")));
            this.textboxArea.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxArea.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textboxArea.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxArea.BorderColorIdle = System.Drawing.Color.Transparent;
            this.textboxArea.BorderRadius = 13;
            this.textboxArea.BorderThickness = 1;
            this.textboxArea.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textboxArea.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxArea.DefaultFont = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textboxArea.DefaultText = "";
            this.textboxArea.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            this.textboxArea.ForeColor = System.Drawing.Color.White;
            this.textboxArea.HideSelection = true;
            this.textboxArea.IconLeft = null;
            this.textboxArea.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxArea.IconPadding = 10;
            this.textboxArea.IconRight = null;
            this.textboxArea.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxArea.Lines = new string[0];
            this.textboxArea.Location = new System.Drawing.Point(371, 257);
            this.textboxArea.MaxLength = 32767;
            this.textboxArea.MinimumSize = new System.Drawing.Size(1, 1);
            this.textboxArea.Modified = false;
            this.textboxArea.Multiline = false;
            this.textboxArea.Name = "textboxArea";
            stateProperties9.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxArea.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textboxArea.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxArea.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Transparent;
            stateProperties12.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            stateProperties12.ForeColor = System.Drawing.Color.White;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxArea.OnIdleState = stateProperties12;
            this.textboxArea.Padding = new System.Windows.Forms.Padding(3);
            this.textboxArea.PasswordChar = '\0';
            this.textboxArea.PlaceholderForeColor = System.Drawing.Color.White;
            this.textboxArea.PlaceholderText = "Enter text";
            this.textboxArea.ReadOnly = false;
            this.textboxArea.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textboxArea.SelectedText = "";
            this.textboxArea.SelectionLength = 0;
            this.textboxArea.SelectionStart = 0;
            this.textboxArea.ShortcutsEnabled = true;
            this.textboxArea.Size = new System.Drawing.Size(122, 39);
            this.textboxArea.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textboxArea.TabIndex = 38;
            this.textboxArea.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textboxArea.TextMarginBottom = 0;
            this.textboxArea.TextMarginLeft = 3;
            this.textboxArea.TextMarginTop = 0;
            this.textboxArea.TextPlaceholder = "Enter text";
            this.textboxArea.UseSystemPasswordChar = false;
            this.textboxArea.WordWrap = true;
            // 
            // textboxPricePerMeter
            // 
            this.textboxPricePerMeter.AcceptsReturn = false;
            this.textboxPricePerMeter.AcceptsTab = false;
            this.textboxPricePerMeter.AnimationSpeed = 200;
            this.textboxPricePerMeter.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textboxPricePerMeter.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textboxPricePerMeter.BackColor = System.Drawing.Color.Transparent;
            this.textboxPricePerMeter.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textboxPricePerMeter.BackgroundImage")));
            this.textboxPricePerMeter.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxPricePerMeter.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textboxPricePerMeter.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxPricePerMeter.BorderColorIdle = System.Drawing.Color.Transparent;
            this.textboxPricePerMeter.BorderRadius = 13;
            this.textboxPricePerMeter.BorderThickness = 1;
            this.textboxPricePerMeter.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textboxPricePerMeter.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxPricePerMeter.DefaultFont = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textboxPricePerMeter.DefaultText = "";
            this.textboxPricePerMeter.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            this.textboxPricePerMeter.ForeColor = System.Drawing.Color.White;
            this.textboxPricePerMeter.HideSelection = true;
            this.textboxPricePerMeter.IconLeft = null;
            this.textboxPricePerMeter.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxPricePerMeter.IconPadding = 10;
            this.textboxPricePerMeter.IconRight = null;
            this.textboxPricePerMeter.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxPricePerMeter.Lines = new string[0];
            this.textboxPricePerMeter.Location = new System.Drawing.Point(547, 257);
            this.textboxPricePerMeter.MaxLength = 32767;
            this.textboxPricePerMeter.MinimumSize = new System.Drawing.Size(1, 1);
            this.textboxPricePerMeter.Modified = false;
            this.textboxPricePerMeter.Multiline = false;
            this.textboxPricePerMeter.Name = "textboxPricePerMeter";
            stateProperties5.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxPricePerMeter.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textboxPricePerMeter.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxPricePerMeter.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Transparent;
            stateProperties8.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            stateProperties8.ForeColor = System.Drawing.Color.White;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxPricePerMeter.OnIdleState = stateProperties8;
            this.textboxPricePerMeter.Padding = new System.Windows.Forms.Padding(3);
            this.textboxPricePerMeter.PasswordChar = '\0';
            this.textboxPricePerMeter.PlaceholderForeColor = System.Drawing.Color.White;
            this.textboxPricePerMeter.PlaceholderText = "Enter text";
            this.textboxPricePerMeter.ReadOnly = false;
            this.textboxPricePerMeter.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textboxPricePerMeter.SelectedText = "";
            this.textboxPricePerMeter.SelectionLength = 0;
            this.textboxPricePerMeter.SelectionStart = 0;
            this.textboxPricePerMeter.ShortcutsEnabled = true;
            this.textboxPricePerMeter.Size = new System.Drawing.Size(122, 39);
            this.textboxPricePerMeter.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textboxPricePerMeter.TabIndex = 39;
            this.textboxPricePerMeter.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textboxPricePerMeter.TextMarginBottom = 0;
            this.textboxPricePerMeter.TextMarginLeft = 3;
            this.textboxPricePerMeter.TextMarginTop = 0;
            this.textboxPricePerMeter.TextPlaceholder = "Enter text";
            this.textboxPricePerMeter.UseSystemPasswordChar = false;
            this.textboxPricePerMeter.WordWrap = true;
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel2.ForeColor = System.Drawing.Color.White;
            this.bunifuLabel2.Location = new System.Drawing.Point(12, 58);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(79, 18);
            this.bunifuLabel2.TabIndex = 40;
            this.bunifuLabel2.Text = "Site Name:";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // textboxSiteName
            // 
            this.textboxSiteName.AcceptsReturn = false;
            this.textboxSiteName.AcceptsTab = false;
            this.textboxSiteName.AnimationSpeed = 200;
            this.textboxSiteName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.textboxSiteName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.textboxSiteName.BackColor = System.Drawing.Color.Transparent;
            this.textboxSiteName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("textboxSiteName.BackgroundImage")));
            this.textboxSiteName.BorderColorActive = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxSiteName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.textboxSiteName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            this.textboxSiteName.BorderColorIdle = System.Drawing.Color.Transparent;
            this.textboxSiteName.BorderRadius = 13;
            this.textboxSiteName.BorderThickness = 1;
            this.textboxSiteName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.textboxSiteName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxSiteName.DefaultFont = new System.Drawing.Font("Century Gothic", 9.818182F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.textboxSiteName.DefaultText = "";
            this.textboxSiteName.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            this.textboxSiteName.ForeColor = System.Drawing.Color.White;
            this.textboxSiteName.HideSelection = true;
            this.textboxSiteName.IconLeft = null;
            this.textboxSiteName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxSiteName.IconPadding = 10;
            this.textboxSiteName.IconRight = null;
            this.textboxSiteName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.textboxSiteName.Lines = new string[0];
            this.textboxSiteName.Location = new System.Drawing.Point(12, 82);
            this.textboxSiteName.MaxLength = 32767;
            this.textboxSiteName.MinimumSize = new System.Drawing.Size(1, 1);
            this.textboxSiteName.Modified = false;
            this.textboxSiteName.Multiline = false;
            this.textboxSiteName.Name = "textboxSiteName";
            stateProperties1.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxSiteName.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.textboxSiteName.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(255)))), ((int)(((byte)(161)))), ((int)(((byte)(10)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxSiteName.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Transparent;
            stateProperties4.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(66)))), ((int)(((byte)(66)))), ((int)(((byte)(76)))));
            stateProperties4.ForeColor = System.Drawing.Color.White;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.textboxSiteName.OnIdleState = stateProperties4;
            this.textboxSiteName.Padding = new System.Windows.Forms.Padding(3);
            this.textboxSiteName.PasswordChar = '\0';
            this.textboxSiteName.PlaceholderForeColor = System.Drawing.Color.White;
            this.textboxSiteName.PlaceholderText = "Enter text";
            this.textboxSiteName.ReadOnly = false;
            this.textboxSiteName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.textboxSiteName.SelectedText = "";
            this.textboxSiteName.SelectionLength = 0;
            this.textboxSiteName.SelectionStart = 0;
            this.textboxSiteName.ShortcutsEnabled = true;
            this.textboxSiteName.Size = new System.Drawing.Size(297, 39);
            this.textboxSiteName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.textboxSiteName.TabIndex = 41;
            this.textboxSiteName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.textboxSiteName.TextMarginBottom = 0;
            this.textboxSiteName.TextMarginLeft = 3;
            this.textboxSiteName.TextMarginTop = 0;
            this.textboxSiteName.TextPlaceholder = "Enter text";
            this.textboxSiteName.UseSystemPasswordChar = false;
            this.textboxSiteName.WordWrap = true;
            // 
            // FormAddSite
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(48)))), ((int)(((byte)(48)))), ((int)(((byte)(58)))));
            this.ClientSize = new System.Drawing.Size(687, 430);
            this.Controls.Add(this.textboxSiteName);
            this.Controls.Add(this.bunifuLabel2);
            this.Controls.Add(this.textboxPricePerMeter);
            this.Controls.Add(this.textboxArea);
            this.Controls.Add(this.buttonAdd);
            this.Controls.Add(this.bunifuLabel9);
            this.Controls.Add(this.textboxLatitude);
            this.Controls.Add(this.bunifuLabel8);
            this.Controls.Add(this.textboxLongitude);
            this.Controls.Add(this.bunifuLabel7);
            this.Controls.Add(this.bunifuLabel6);
            this.Controls.Add(this.textboxStreet);
            this.Controls.Add(this.bunifuLabel5);
            this.Controls.Add(this.textboxCity);
            this.Controls.Add(this.bunifuLabel4);
            this.Controls.Add(this.textboxCountry);
            this.Controls.Add(this.bunifuLabel3);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FormAddSite";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "formSiteAdderorSelector";
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuImageButton bunifuImageButton1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.Framework.UI.BunifuElipse bunifuElipse1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel5;
        private Bunifu.UI.WinForms.BunifuTextBox textboxCity;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox textboxCountry;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel9;
        private Bunifu.UI.WinForms.BunifuTextBox textboxLatitude;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel8;
        private Bunifu.UI.WinForms.BunifuTextBox textboxLongitude;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel7;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel6;
        private Bunifu.UI.WinForms.BunifuTextBox textboxStreet;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton buttonAdd;
        private Bunifu.UI.WinForms.BunifuTextBox textboxPricePerMeter;
        private Bunifu.UI.WinForms.BunifuTextBox textboxArea;
        private Bunifu.UI.WinForms.BunifuTextBox textboxSiteName;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
    }
}